### ISSUE TITLE
Doesn't launch on Ubuntu 20.10

### ISSUE THREAD

**Issue by abhishekpc** [KrispyCamel4u/SysMonTask#2]
Hi,

I was trying to cover it on itsfoss.com

Installed the application via the PPA but when I try to run it, it doesn't start and crashes.

In the terminal, it shows the following error message:

`sudo sysmontask
[sudo] password for abhishek: 
/usr/lib/python3/dist-packages/sysmontask/sysmontask.py:5: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go
/usr/lib/python3/dist-packages/sysmontask/proc.py:1: PyGIWarning: Wnck was imported without specifying a version first. Use gi.require_version('Wnck', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as g , GLib as go,GdkPixbuf,Wnck, Gio
acquired root permission

(sysmontask:11757): Gtk-WARNING **: 17:26:28.271: Could not load image 'SysMonTask.png': Failed to open file “/usr/share/sysmontask/glade_files/SysMonTask.png”: No such file or directory

(sysmontask:11757): Gtk-WARNING **: 17:26:28.276: Could not load image 'usr/share/sysmontask/icons/SysMonTask.png': Failed to open file “/usr/share/sysmontask/glade_files/usr/share/sysmontask/icons/SysMonTask.png”: No such file or directory
memory tab initialising
nvme0n1
/bin/sh: 1: nvidia-smi: not found
no nvidia gpu found
Traceback (most recent call last):
  File "/usr/bin/sysmontask", line 33, in <module>
    sys.exit(load_entry_point('sysmontask==1.1.0', 'console_scripts', 'sysmontask')())
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 555, in start
    main=myclass()
  File "/usr/lib/python3/dist-packages/sysmontask/sysmontask.py", line 93, in __init__
    self.procinitialisation()
  File "/usr/lib/python3/dist-packages/sysmontask/proc.py", line 248, in procInit
    self.processSystemd=ps.Process(self.systemdId)
AttributeError: 'myclass' object has no attribute 'systemdId'
`

**Comment by KrispyCamel4u** [comment]
Hi, Thank you so much for reporting it.

By tonight, a newer version with a couple of other new feature will be added and this bugs with others will be fixed. Please wait till then.

I will be ping you when that is done.

**Comment by KrispyCamel4u** [comment]
Hi, 
I have fixed the issue :) with a couple of other features.
Please update me if it works for you or in case of any other issue.

**Comment by abhishekpc** [comment]
I confirm that the new version now launches and works on Ubuntu 20.10. I'll cover it on itsfoss.com next Monday.

**Comment by KrispyCamel4u** [comment]
Thank you, for your support for this project :)
